name: Update Archive

on:
  schedule:
    - cron: "0 0,12 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-archiver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.COMMIT_PAT }}
      - name: Install dependencies
        run: npm i
      - name: Healthcheck Start
        env:
          HEALTHCHECK_URL: ${{ secrets.HEALTHCHECK_URL }}
        run: curl "$HEALTHCHECK_URL/start"
      - name: Update archive
        run: ./run.sh
      - name: Prepare Git
        run: |
          git config --global user.name 'archiver action'
          git config --global user.email 'harvesthill@users.noreply.github.com'
      - name: Stage
        run: git add .
      - name: Commit
        run: git diff --quiet --exit-code || git commit -m "update archive as of $(date +%F_%T)"
      - name: Push
        run: git push
      - name: Healthcheck End
        env:
          HEALTHCHECK_URL: ${{ secrets.HEALTHCHECK_URL }}
        run: curl "$HEALTHCHECK_URL"