# This is a basic workflow to help you get started with Actions

name: Update Archive

on:
  schedule:
    - cron: "0 0 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm i
      - name: Update archive
        run: ./run.sh
      - name: Commit
        run: |
          git config --global user.name 'archiver action'
          git config --global user.email 'harvesthill@users.noreply.github.com'
          git commit -am "update archive"
          git push
